title: 
author: The QES Team
logo: logo.png

# Force re-execution of notebooks on each build.
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex
  latex_engine: xelatex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://quantitative-environmental-science.github.io/Notes/  # Online location of your book
  branch: gh_pages  # Which branch of the repository should be used when creating links (optional)

html:
  favicon: favicon.png

sphinx:
  config:
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    mathjax3_config:
      loader:
        load: ['[tex]/physics', '[tex]/ams']
      tex:
        packages: ['base', 'physics', 'ams']
    language: en
    latex_elements:
      preamble: |
        \newcommand{\dv}[2]{\frac{\mathrm{d}#1}{\mathrm{d}#2}}  % replaces physics.sty \dv
        \newcommand{\dd}{\mathrm{d}}  % replaces physics.sty \dd
        \setcounter{chapter}{1}  % to make the chapter numbering correct (although thrown out later by intro chapters...)
        \makeatletter \renewcommand{\@chapapp}{Lecture} \makeatother  % change 'Chapter' to 'Lecture'
      pointsize: 11pt
      papersize: a4paper
